spring:
  application:
    name: store-server
  cloud:
    nacos:
      config:
        server-addr: 1.117.70.65:8848
        username: nacos
        password: nacosstart
        namespace: cq_hxc
        shared-configs:
          - data-id: redis_config.yml
          - data-id: mybatis_config.yml
          - data-id: nacos_discovery.yml


  config:
    import:
      - optional:nacos:user-server.yml
      - optional:nacos:redis_config.yml
      - optional:nacos:mybatis_config.yml
      - optional:nacos:nacos_discovery.yml

#      discovery:
#        server-addr: 1.117.70.65:8848
#        username: nacos
#        password: nacosstart



#  datasource:
#    url: jdbc:mysql://8.130.24.40:3366/ch_store?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
#    username: root
#    password: cq_hxc_mysql_3366
#    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  # 配置mapper的扫描，找到所有的mapper.xml映射文件
#  mapperLocations: classpath:mapper/**/*Mapper.xml
#  configuration:
#    cache-enabled: false
#    useGeneratedKeys: true
#    defaultExecutorType: SIMPLE
#    mapUnderscoreToCamelCase: true
#    interceptors:
#      - com.example.mybatisPlugin.plugin.impl.CacheInterceptor

#  redis:
#    host: 8.130.24.40
#    port: 6666
#    password: cq_hxc_redis_6666
#    database: 0
#    timeout: 10s
#    lettuce:
#      pool:
#        # 连接池中的最小空闲连接
#        min-idle: 0
#        # 连接池中的最大空闲连接
#        max-idle: 8
#        # 连接池的最大数据库连接数
#        max-active: 8
#        # #连接池最大阻塞等待时间（使用负值表示没有限制）
#        max-wait: -1ms
