spring:
  application:
    name: user-server
  cloud:
    nacos:
      config:
        server-addr: 1.117.70.65:8848
        username: nacos
        password: nacosstart
        namespace: cq_hxc
        shared-configs:
          - data-id: redis_config.yml
          - data-id: mybatis_config.yml
          - data-id: nacos_discovery.yml


  config:
    import:
      - optional:nacos:user-server.yml
      - optional:nacos:redis_config.yml
      - optional:nacos:mybatis_config.yml
      - optional:nacos:nacos_discovery.yml
